name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build backend Docker image
      run: |
        docker build . --file popcorn-backend/Dockerfile --tag qianlu0826/popcorn:backend-latest
        docker push qianlu0826/popcorn:backend-latest
    - name: Build frontend Docker image
      run: |
        docker build . --file popcorn-frontend/Dockerfile --tag qianlu0826/popcorn:frontend-latest
        docker push qianlu0826/popcorn:frontend-latest
